### ISSUE TITLE
一个反馈

### ISSUE THREAD

**Issue by RuCu6** [zmqcherish/proxy-script#10]
佬，我又来了。你更新日志为什么取消了这个啊

~~删除发现页(tab3)轮播广告图~~

这个位置的广告也很碍眼啊

![13EA78F4-EC9D-4D28-9161-EE73A35CBE8E](https://user-images.githubusercontent.com/49463634/168707001-eeea39d8-cf40-410d-a0c8-8ff9050cc024.png)

**Comment by zmqcherish** [comment]
【05.22更新】（重新）删除发现页(tab3)轮播广告图，需要配置weibo_config.js -> removeSearchWindow为true。其实轮播中有些不是广告，一起杀

**Comment by RuCu6** [comment]
现在这个时间 7个tab已经全是广告了

**Comment by RuCu6** [comment]
非常感谢
