### ISSUE TITLE
iOS微博 12.6.3去广告问题

### ISSUE THREAD

**Issue by alexchoi33** [zmqcherish/proxy-script#18]
iOS 最新的的微博 12.6.3去广告问题
12.6.3首页广告依然存在，表现为下载/更新后立即使用没有广告，待放在后台半小时以上再次进去微博就出现广告。删除再重新下载仍然循环出现上述情况
降级版本到12.6.1则无此问题出现

**Comment by zmqcherish** [comment]
12.7.0 版本没复现。另外请问iOS还能降级版本安装？

**Comment by alexchoi33** [comment]
在另外一个机器上测试，最近确实没复现。但是提交issue时候两台机子都是同样情况😂

iOS 可以实现App降级安装，通过iTunes配合Fiddle抓包下载旧版本app，再使用爱思助手进行安装
