### ISSUE TITLE
请求更新

### ISSUE THREAD

**Issue by RuCu6** [zmqcherish/proxy-script#19]
去开屏广告已失效
新版微博加入了更多推广（如图）

辛苦大佬更新一下♥️♥️
![8AF5F6CF-7FED-4E69-ABA9-B4EE6D2190E4](https://user-images.githubusercontent.com/49463634/177893866-181e9fb1-fa9d-45a2-b9d5-0be4e42b6daa.jpeg)
![FBE7FEE7-F240-4FEB-B0D6-E15D5FE3E1B1](https://user-images.githubusercontent.com/49463634/177893872-46d339e9-0780-4df6-9541-539e58238454.jpeg)

**Comment by zmqcherish** [comment]
p2已处理

**Comment by RuCu6** [comment]
佬 终于等到你🥰🥰

**Comment by zmqcherish** [comment]
p1已处理
