### ISSUE TITLE
评论下有广告和推荐无法去除。

### ISSUE THREAD

**Issue by Jarv1s0** [zmqcherish/proxy-script#2]
大佬可以参考下这个微博去广告，https://github.com/yjqiang/surge_scripts/tree/main/scripts/weibo
他的评论区广告去的很干净。另外开了微博去广告之后，长图加载很慢。大佬闲了可以看看。

**Comment by zmqcherish** [comment]
你用了weibo_config.js 文件的自定义功能吗？ @Jarv1s0

**Comment by Jarv1s0** [comment]
用了，按照你写的配置，订阅了。

**Comment by zmqcherish** [comment]
> 用了，按照你写的配置，订阅了。

我这边使用weibo_config.js 文件的自定义配置一些变量后评论区就没广告了。我再查查吧。。

**Comment by Jarv1s0** [comment]
> > 用了，按照你写的配置，订阅了。
> 
> 我这边使用weibo_config.js 文件的自定义配置一些变量后评论区就没广告了。我再查查吧。。

麻烦啦，你看我给你贴的那个作者，使用他那个之后，评论区广告就没有啦。

**Comment by zmqcherish** [comment]
> > > 用了，按照你写的配置，订阅了。
> > 
> > 
> > 我这边使用weibo_config.js 文件的自定义配置一些变量后评论区就没广告了。我再查查吧。。
> 
> 麻烦啦，你看我给你贴的那个作者，使用他那个之后，评论区广告就没有啦。

麻烦给个具体的微博链接，我这边查看下

**Comment by Jarv1s0** [comment]
> > > > 用了，按照你写的配置，订阅了。
> > > 
> > > 
> > > 我这边使用weibo_config.js 文件的自定义配置一些变量后评论区就没广告了。我再查查吧。。
> > 
> > 
> > 麻烦啦，你看我给你贴的那个作者，使用他那个之后，评论区广告就没有啦。
> 
> 麻烦给个具体的微博链接，我这边查看下

https://m.weibo.cn/1664207987/4699058847616050
![Uploading 31AE5F6D-588D-4D73-8EBD-88DA2C59AA14.png…]()

**Comment by zmqcherish** [comment]
@Jarv1s0 你好，我这边打开评论区是没有广告的，是不是存在脚本冲突问题。你可以试试只打开我的脚本尝试看看。

**Comment by Jarv1s0** [comment]
现在已经好啦，感谢回复。
