### ISSUE TITLE
一个请求

### ISSUE THREAD

**Issue by RuCu6** [zmqcherish/proxy-script#22]
佬 可以去掉这些东西吗？

1.微博首页顶部的直播通知
2.首页右上角红包🧧
3.微博下发的配置信息，如各种活动和节日背景

![875AE3EF-8D0A-47F3-BA85-F2BE9E63213B](https://user-images.githubusercontent.com/49463634/180591559-5c2b0981-0f6e-4f9a-83bb-9a9bbf455c7a.jpeg)
![FBCDBE6A-777B-47B0-BD72-0CA724C43B3B](https://user-images.githubusercontent.com/49463634/182016586-1ace2dda-8d6a-4579-81b1-6b518d3ec503.jpeg)
![6D91AE44-8EDF-4320-869B-9161CCF1852F](https://user-images.githubusercontent.com/49463634/182323111-b10d2b1f-5fdc-46a4-984c-cd6bf6e3d6db.jpeg)

**Comment by zmqcherish** [comment]
直播的在weibo_config中removeLiveMedia变量设置

**Comment by RuCu6** [comment]
参数一直都是true  有时会失效
