### ISSUE TITLE
部分菜单配置不起作用

### ISSUE THREAD

**Issue by RuCu6** [zmqcherish/proxy-script#27]
脚本是最新版

mblog_menus_avatar_widget:false,
mblog_menus_card_bg: false,
mblog_menus_follow:false,

清除微博缓存 重新进入微博
头像挂件仍然加载
卡片貌似成功清除
关注按钮仍在存在

**Comment by RuCu6** [comment]
![20C2371B-5FFE-4D84-8387-3C3F54CA729F](https://user-images.githubusercontent.com/49463634/185970327-5f5e33ae-44ec-4714-8dd6-e2ead01f87a7.jpeg)

**Comment by zmqcherish** [comment]
你可能没理解这个菜单配置的作用，这里的配置，只是指“是否有这个菜单选项”，出发点是精简单挑微博详情页的菜单，并不是对页面产生具体影响

**Comment by RuCu6** [comment]
抱歉  理解错了。挂件那个是不是确实有问题？
