### ISSUE TITLE
去广告问题

### ISSUE THREAD

**Issue by spirytuslove** [zmqcherish/proxy-script#3]
评论区的广告好像没法去除 另外自定义皮肤用的官方皮肤关掉后台后再进入就失效了

**Comment by zmqcherish** [comment]
你运行了自定义配置了吗？皮肤失效有提示吗？非会员？
最好有点详细的操作或截图，不然不方便排查

**Comment by spirytuslove** [comment]
圈X安装了https://raw.githubusercontent.com/zmqcherish/proxy-script/main/weibo.conf重写  然后登微博设置会员皮肤 首次设置底部tab图标变成会员皮肤的tab图片 但是把微博后台关掉再登录又变成默认原始tab皮肤图标

**Comment by zmqcherish** [comment]
目前非会员确实自定义皮肤会失效，我排查下。

**Comment by zmqcherish** [comment]
已修复，请使用最新版v0422.1 @spirytuslove

**Comment by spirytuslove** [comment]
好的我试试感谢
