### ISSUE TITLE
微博轻享版（原微博国际）能加下去广告吗

### ISSUE THREAD

**Issue by idewindy** [zmqcherish/proxy-script#36]

**Comment by srk24** [comment]
你用这个试试
https://raw.githubusercontent.com/srk24/profile/master/surge/module/weibo_intl.sgmodule

**Comment by ZephyrZY** [comment]
@srk24 大佬，失效了呀😭

**Comment by ZephyrZY** [comment]
@srk24 大佬，信息流广告去不掉呀😭

**Comment by srk24** [comment]
> @srk24 大佬，信息流广告去不掉呀😭

没有吧，重装微博试试看

**Comment by ZephyrZY** [comment]
大佬，我重装了微博国际版，登陆的时候没有，退出之后再进去信息流广告又有了> > @srk24 大佬，信息流广告去不掉呀😭
> 
> 
> 
> 没有吧，重装微博试试看

**Comment by srk24** [comment]
> 

我测试下来正常。
环境：surge 5.1.3 、微博轻享版5.9.8

**Comment by ZephyrZY** [comment]
@srk24 我微博版本和您一样，用的圈叉，版本是1.1.0-767，配置是墨鱼手记一键规则，和几条机神的重写，以前好好的，最近几天才失效的，一刷全是广告，很烦人

**Comment by srk24** [comment]
> @srk24 我微博版本和您一样，用的圈叉，版本是1.1.0-767，配置是墨鱼手记一键规则，和几条机神的重写，以前好好的，最近几天才失效的，一刷全是广告，很烦人

我尝试用quan-x 1.1.0-767，将微博轻享版卸载重装，重新打开，依旧没有复现。因此请自行检查是否是与其他规则冲突。

**Comment by ZephyrZY** [comment]
感谢大佬，辛苦您了

**Comment by idewindy** [comment]
> 你用这个试试
> [surge module](https://raw.githubusercontent.com/srk24/profile/master/surge/module/weibo_intl.sgmodule)
> [quanx rewrite](https://raw.githubusercontent.com/srk24/profile/master/quanx/rewrite/weibo_intl.conf)
