### ISSUE TITLE
微博私信无法删除

### ISSUE THREAD

**Issue by Scheme4u** [zmqcherish/proxy-script#38]
作者你好👋
在使用微博去广告脚本时，遇到了这样棘手的问题，同时也确定了只有在开启代理软件中的微博去广告脚本时才会出现这个问题，即微博上的私信聊天窗口无法删除，会弹窗提示删除失败，但是点赞和评论的红点提示仍可以正常清除。
我使用qx查到的日志目前只知道rewrite中的reject这一类😂 如果需要更多细节可以再联系🙏
![36737DCA-6FF5-4460-87D2-A8D96C6C19E8](https://user-images.githubusercontent.com/58000512/196405261-14aaab8c-45d6-467d-911e-97740192d72e.png)
![B98DF64F-A2C7-4764-9021-69F4A916C264](https://user-images.githubusercontent.com/58000512/196405276-e44b680a-7cc1-4d12-94e4-47ff95d60864.png)

**Comment by RuCu6** [comment]
很简单  把你reject的微博相关域名全部直连  都用脚本了干嘛还用规则这么简单粗暴一刀切的做法？

**Comment by Scheme4u** [comment]
> 很简单 把你reject的微博相关域名全部直连 都用脚本了干嘛还用规则这么简单粗暴一刀切的做法？

这个是脚本自带的重写规则，修改的时候还提示来自远程配置的规则无法修改🆘

**Comment by RuCu6** [comment]
新建一模一样的同名规则 改成直连 放在filter_local  本地优先级高于远程规则

**Comment by zmqcherish** [comment]
我的脚本没有配置以上reject规则，是不是引用了其他人的脚本

**Comment by Scheme4u** [comment]
> 新建一模一样的同名规则 改成直连 放在filter_local 本地优先级高于远程规则

还能这样做，长见识了，谢谢♥
