### ISSUE TITLE
一个小请求

### ISSUE THREAD

**Issue by RuCu6** [zmqcherish/proxy-script#6]
佬，微博首页右下角这个卡片推广可以去掉吗？
![5CF71886-E4D1-4276-A1DB-58AD04E382D5](https://user-images.githubusercontent.com/49463634/164666796-6c91a715-baff-4f19-822f-d60dd0682d05.png)

**Comment by zmqcherish** [comment]
节后我研究一下

**Comment by RuCu6** [comment]
感谢回复🥳
