### ISSUE TITLE
发现页轮播广告

### ISSUE THREAD

**Issue by spirytuslove** [zmqcherish/proxy-script#7]
问下能否下之前一样支持发现页轮播广告去除 另外圈叉里面本地脚本看不到版本号能在哪里查看脚本版本是不是最新的
![EEB229A3-DDD4-450D-989E-DA70251971AE](https://user-images.githubusercontent.com/64483414/165409505-db79c994-5593-4651-bca9-7f9cf621206a.png)

**Comment by zmqcherish** [comment]
1. 因为发现页的轮播图广告，是图片右上角带“广告”字，是“假”广告，无法正确区分非广告和广告，所以没做去除
2. 在重写tab下，找到对应的重写规则右边的“超链接”图标，点击选择“查看脚本”，weibo_main.js脚本才有版本，launch目前不显示版本

**Comment by spirytuslove** [comment]
> * 因为发现页的轮播图广告，是图片右上角带“广告”字，是“假”广告，无法正确区分非广告和广告，所以没做去除
> * 在重写tab下，找到对应的重写规则右边的“超链接”图标，点击选择“查看脚本”，weibo_main.js脚本才有版本，launch目前不显示版本

感谢回复 另外自定义开屏图片/视频这功能也很好棒啊 希望大佬后期可以开发
