### ISSUE TITLE
微博广告

### ISSUE THREAD

**Issue by RuCu6** [zmqcherish/proxy-script#8]
微博的广告真的是层出不穷
商店最新版，我的页面又多了横幅广告
可以干掉他吗😝

![AD0C67F0-048B-4C27-9F1C-D7F153303AE6](https://user-images.githubusercontent.com/49463634/167365395-529d7a9a-0717-47c2-af0e-ad1e89dac86b.jpeg)

**Comment by zmqcherish** [comment]
这个简单 明天干掉:)

**Comment by RuCu6** [comment]
这速度。爱了爱了:smile:

**Comment by zmqcherish** [comment]
> 这速度。爱了爱了😗

已解决，有问题再联系。

**Comment by RuCu6** [comment]
:thumbsup:
